# ---------- Stage 1: Build ----------
FROM maven:3.9.9-eclipse-temurin-17-alpine AS builder

WORKDIR /app

# Cache Maven dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source code and build package
COPY src ./src
RUN mvn clean package -DskipTests


# ---------- Stage 2: Runtime ----------
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Create non-root user for security
RUN addgroup -S spring && adduser -S -u 10014 spring -G spring

# Copy compiled JAR from Stage 1 (builder)
COPY --from=builder /app/target/*.jar app.jar
RUN chown spring:spring app.jar
USER 10014

EXPOSE 80

# Fast JVM execution flags for Vercel Serverless
ENTRYPOINT ["java", \
  "-XX:+TieredCompilation", \
  "-XX:TieredStopAtLevel=1", \
  "-Xms128m", \
  "-Xmx384m", \
  "-Xss256k", \
  "-Djava.security.egd=file:/dev/./urandom", \
  "-jar", "app.jar"]