spring.application.name=arthabook-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.open-in-view=false